import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Toaster } from "sonner";
import MySessionProvider from "./_providers/MySessionProvider";
import CartContextProvider from "./_context/CartContextProvider";
import { getUserCart } from "./_actions/cart.actions";
import { getServerSession } from "next-auth";
import { nextAuthConfig } from "@/lib/nextauth.config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthConfig)
  
  let userCart = null
  
  // Only fetch cart if user is authenticated
  if (session) {
    userCart = await getUserCart().catch(() => null)
  }


  return (
    <html
      lang="en"
    >
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} suppressHydrationWarning>
        
        {/* <SessionProvider> */}

        <MySessionProvider>


              <CartContextProvider userCart={userCart} >


              <Toaster/>
              <Navbar  />
              {children}


              </CartContextProvider>



        </MySessionProvider>


         

        {/* </SessionProvider> */}
        
        </body>
    </html>
  );
}
